plugins {
	id 'java'
}

repositories {
	maven {
		url = 'https://repo.runelite.net'
		content {
			includeGroupByRegex("net\\.runelite.*")
		}
	}
	mavenCentral()
}

def runeLiteVersion = '1.12.28'

dependencies {
	compileOnly group: 'net.runelite', name:'client', version: runeLiteVersion

	compileOnly 'org.projectlombok:lombok:1.18.30'
	annotationProcessor 'org.projectlombok:lombok:1.18.30'

	testImplementation 'junit:junit:4.12'
	testImplementation group: 'net.runelite', name:'client', version: runeLiteVersion
	testImplementation group: 'net.runelite', name:'jshell', version: runeLiteVersion
}

group = 'com.amtrollin.xtremetasker'
version = '1.0.0'

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release.set(11)
}

processResources {
    exclude 'task_data/taskbak.json'
    exclude 'task_data/tasks_v1*.csv'
    exclude 'task_data/utils/**'
    exclude 'utils/**'
}

tasks.register('shadowJar', Jar) {
    dependsOn classes

    manifest {
        attributes(
                'Main-Class': 'com.amtrollin.xtremetasker.XtremeTaskerPlugin',
                'Multi-Release': true
        )
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from sourceSets.main.output

    exclude 'META-INF/INDEX.LIST'
    exclude 'META-INF/*.SF'
    exclude 'META-INF/*.DSA'
    exclude 'META-INF/*.RSA'
    exclude '**/module-info.class'

    group = BasePlugin.BUILD_GROUP
    archiveClassifier.set('shadow')
    archiveFileName.set("${rootProject.name}-${project.version}-all.jar")
}
