displayName=Xtreme Tasker
author=AmTrollin
description=Task list + tracking overlay for OSRS
tags=task,tasks,goals,overlay
plugins=com.amtrollin.xtremetasker.XtremeTaskerPlugin
plugin-class=com.amtrollin.xtremetasker.XtremeTaskerPlugin
build=standard
