displayName=Xtreme Tasker
author=AmTrollin
description=Random task generator and progress tracker for Combat Achievements and Collection Log tasks
tags=task,tasks,goals,overlay,collection,combat
plugins=com.amtrollin.xtremetasker.XtremeTaskerPlugin
build=standard
